<<<<<<< HEAD
-- -- 사진 테이블
-- create table photo
-- (
--     photo_id int generated by default as identity,
--     photo_name varchar(500) not null,
--     photo_image varchar(500) not null,
--     photo_people_count int not null,
--     photo_created_at varchar(255) not null,
--     primary key (photo_id)
-- );
--
-- -- 사진첩 테이블
-- create table album
-- (
--     album_id int generated by default as identity,
--     album_name varchar(500) not null,
--     album_created_at varchar(255) not null,
--     primary key (album_id)
-- );
--
-- -- 사용자 테이블
-- create table user
-- (
--     user_id int generated by default as identity,
--     user_email varchar(500) not null,
--     user_password varchar(255) not null,
--     user_nickname varchar(255) not null,
--     album_id int,
--     primary key (user_id)
-- );
--
-- -- 사용자_사진첩 테이블
-- create table user_album
-- (
--     user_album_id int generated by default as identity,
--     user_id int not null,
--     album_id int not null,
--     primary key (user_album_id)
-- );
=======
-- 사진 테이블
create table userPhoto
(
    photo_id int generated by default as identity,
    photo_name varchar(500) not null,
    photo_image varchar(500) not null,
    photo_people_count int not null,
    photo_created_at varchar(255) not null,
    primary key (photo_id)
);

-- 사진첩 테이블
create table album
(
    album_id int generated by default as identity,
    album_name varchar(500) not null,
    album_created_at varchar(255) not null,
    primary key (album_id)
);

-- 사용자 테이블
create table user
(
    user_id int generated by default as identity,
    user_email varchar(500) not null,
    user_password varchar(255) not null,
    user_nickname varchar(255) not null,
    album_id int,
    primary key (user_id)
);

-- 사용자_사진첩 테이블
create table user_album
(
    user_album_id int generated by default as identity,
    user_id int not null,
    album_id int not null,
    primary key (user_album_id)
);
>>>>>>> develop
